services:
  rota-showcase:
    image: rotaract/rota-showcase:latest
    container_name: rota-showcase
    
    ports:
      - "3000:3000"
    build:
      context: .
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_OLA_MAPS_API_KEY: ${NEXT_PUBLIC_OLA_MAPS_API_KEY}
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    restart: unless-stopped

    expose:
      - "3000"

    env_file:
      - /opt/config/reporting.env
      - .env

    networks:
      - default
      - rotaract

networks:
  default:

  rotaract:
    external: true
