/**
 * Auto-generated database types via Supabase CLI (Mocked for scaffolding)
 */
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      districts: {
        Row: {
          id: string
          name: string
          number: string
          logo_url: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          name: string
          number: string
          logo_url?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          name?: string
          number?: string
          logo_url?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Relationships: []
      }
      clubs: {
        Row: {
          id: string
          district_id: string
          name: string
          slug: string
          status: 'ACTIVE' | 'INACTIVE' | 'SUSPENDED'
          founded_date: string | null
          charter_date: string | null
          logo_url: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          district_id: string
          name: string
          slug: string
          status: 'ACTIVE' | 'INACTIVE' | 'SUSPENDED'
          founded_date?: string | null
          charter_date?: string | null
          logo_url?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          district_id?: string
          name?: string
          slug?: string
          status?: 'ACTIVE' | 'INACTIVE' | 'SUSPENDED'
          founded_date?: string | null
          charter_date?: string | null
          logo_url?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Relationships: []
      }
      member_profiles: {
        Row: {
          id: string
          auth_id: string
          club_id: string | null
          first_name: string
          last_name: string
          email: string
          phone: string | null
          blood_group: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          auth_id: string
          club_id?: string | null
          first_name: string
          last_name: string
          email: string
          phone?: string | null
          blood_group?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          auth_id?: string
          club_id?: string | null
          first_name?: string
          last_name?: string
          email?: string
          phone?: string | null
          blood_group?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Relationships: []
      }
      member_roles: {
        Row: {
          id: string
          member_id: string
          role: string
          assigned_at: string
          expires_at: string | null
          assigned_by: string | null
        }
        Insert: {
          id?: string
          member_id: string
          role: string
          assigned_at?: string
          expires_at?: string | null
          assigned_by?: string | null
        }
        Update: {
          id?: string
          member_id?: string
          role?: string
          assigned_at?: string
          expires_at?: string | null
          assigned_by?: string | null
        }
        Relationships: []
      }
      [key: string]: any
      // Note: Full types for the remaining 15 tables will be auto-generated by Supabase CLI in production
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
