/**
 * Auto-generated database types via Supabase CLI (Mocked for scaffolding)
 */
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      districts: {
        Row: {
          id: string
          name: string
          number: string
          logo_url: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['districts']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['districts']['Insert']>
      }
      clubs: {
        Row: {
          id: string
          district_id: string
          name: string
          slug: string
          status: 'ACTIVE' | 'INACTIVE' | 'SUSPENDED'
          founded_date: string | null
          charter_date: string | null
          logo_url: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['clubs']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['clubs']['Insert']>
      }
      member_profiles: {
        Row: {
          id: string
          auth_id: string
          club_id: string | null
          first_name: string
          last_name: string
          email: string
          phone: string | null
          blood_group: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['member_profiles']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['member_profiles']['Insert']>
      }
      // Note: Full types for the remaining 15 tables will be auto-generated by Supabase CLI in production
    }
  }
}
